apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: garbagedisposal
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: garbagedisposal
subjects:
- kind: ServiceAccount
  name: {{ include "garbagedisposal.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}