apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: garbagedisposal
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - get
      - list
      - update
      - delete

