apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: garbagedisposal
  namespace: {{ .Release.Namespace | quote }}
rules:          # Authorization rules for this role
  - apiGroups:  # 1st API group
      - apps    # An empty string designates the core API group.
    resources:
      - pods
    verbs:
      - get
      - list
      - update
